FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

COPY python-hello-world/app.py /app/python-hello-world/ 
COPY python-hello-world/requirements.txt /app/python-hello-world/
WORKDIR /app/python-hello-world
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]