FROM python:alpine
COPY python-greeter-service/app.py /app/python-greeter-service/ 
COPY python-greeter-service/requirements.txt /app/python-greeter-service/
WORKDIR /app/python-greeter-service
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
