# Default values for cicd-multi-service-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
buildNumber: 1
branch: dev_1
environment: DEV-INT
replicaCount: 3
dnsPolicy: ClusterFirst
restartPolicy: Always
terminationGracePeriodSeconds: 30
serviceType: python-greeter-service
image:
  organization: quay.io/snsumner75
  pullPolicy: IfNotPresent
service:
  externalPort: 5001
  internalPort: 5001
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
