apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.serviceType }}"
  labels:
   chart: "{{ .Chart.Name }}-{{ .Values.serviceType }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
    name: {{ template "fullname" . }}
  selector:
    app: {{ template "fullname" . }}
